language: swift
osx_image: xcode11.1

cache:
  directories:
    - Carthage
    - .build

before_install:
  - brew bundle
  - carthage update --cache-builds

script:
  - xcodebuild clean test -project SwiftyKeychainKit.xcodeproj -scheme SwiftyKeychainKit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1' | xcpretty
